avList = {
"QQProtect.exe": "腾讯QQ",
"WechatBrowser.exe": "微信内置浏览器",
"sslvpn-client.exe": "sslvpn-client",
"WeChatApp.exe": "微信",
"贵州高速.exe": "贵州高速",
"360se.exe": "360安全浏览器",
"et.exe": "金山表格",
"wps.exe": "WPS",
"javaw.exe": "java",
"SogouCloud.exe": "搜狗拼音",
"DingTalk.exe": "钉钉",
"chrome.exe": "谷歌浏览器",
"360bdoctor.exe": "360浏览器安全医生",
"EXCEL.exe": "office办公软件",
"steam.exe": "Steam",
"mdm.exe": "Windows管理控制台",
"WmiPrvSE.exe": "Windows WMI Provider Host",
"inetinfo.exe": "Windows IIS Admin Service Helper",
"Imjpmig.ex": "Windows输入法编辑器",
"Ose.exe": "Microsoft Office源引擎",
"iexplore.exe": "IE浏览器",
"wow.exe": "魔兽世界",
"starcraft.exe": "星际争霸",
"war3.exe": "魔兽争霸",
"warcraft.exe": "魔兽争霸",
"QSanguosha.exe": "太阳神三国杀",
"cstrike.exe": "CS",
"WinKawaks.exe": "街机模拟器",
"aoe2.exe": "帝国时代2",
"GTA.exe": "侠盗车手",
"GTA4.exe": "侠盗车手",
"orochiztc.exe": "无双大蛇Z",
"XMen3.exe": "X战警3",
"prototype.exe": "虐杀原型",
"Torchlight.exe": "火炬之光",
"left4dead.exe": "求生之路",
"left4dead2.exe": "求生之路",
"KillingFloor.exe": "杀戮空间",
"Minecraft.exe": "我的世界",
"CODwaw.exe": "使命召唤",
"CODwawmp.exe": "使命召唤",
"QQgame.exe": "QQ游戏",
"qqmusic.exe": "QQ音乐",
"QiyiService.exe": "爱奇艺",
"QQliveservice.exe": "腾讯视频",
"cloudmusic.exe": "网易云音乐",
"360DesktopLite64.exe": "360桌面助手",
"NewSearchLite.exe": "360搜索",
"SeAppService.exe": "Iomega Zip Drive驱动相关程序",
"360UDiskPro.exe": "360U盘助手模块",
"LISFService.exe": "联想电脑管家",
"sslvpn-service.exe": "sslvpn-service",
"LenovoServiceAS.exe": "联想软件商店",
"LenovoPcManagerService.exe": "联想电脑管家",
"LAVService.exe": "联想电脑管家",
"OfficeClickToRun.exe": "Office",
"LMS.exe": "英特尔本地管理服务",
"wsctrl.exe": "火绒",
"wsctrlsvc.exe": "火绒",
"WeChat.exe": "微信",
"ldnews.exe": "雷电模拟器",
"firefox.exe": "火狐浏览器",
"java.exe ": "java",
"EvernoteSubprocess.exe": "印象笔记",
"EvernoteClipper.exe": "印象笔记",
"Evernote.exe": "印象笔记",
"Everything.exe": "Everything搜索",
"finalshell.exe": "finalshell",
"xshell.exe": "Xshell",
"HiPC.exe": "HiPC",
"mysql.exe": "Mysql",
"mysqld.exe": "Mysql",
"mysqlshow.exe": "Mysql",
"redis-server.exe": "Redis",
"redis-cli.exe": "Redis",
"redis.exe": "Redis",
"Clash for Windows.exe": "Clash",
"msedge.exe": "edge浏览器",
"nessus-service.exe": "Nessus",
"nessusd.exe": "Nessus",
"OfficeClickToRun.exe": "Office",
"openvpn-gui.exe": "OpenVPN",
"openvpn.exe": "OpenVPN",
"pg_ctl.exe": "PostgreSQL数据库管理程序",
"Rolan.exe": "Rolan",
"vmtoolsd.exe": "VMware Service",
"Wireshark.exe": "Wireshark",
"navicat.exe": "Navicat",
"putty.exe": "Putty",
"clash-win64.exe": "Clash",
"sensor-bridge.exe": "Node",
"Node.exe": "Node",
"securecrt.exe": "SecureCRT",
"dbeaver.exe": "dbeaver",
"dumpcap.exe": "Wireshark",
"Thunder.exe": "迅雷下载器",
"notepad++.exe": "NotePad++",
"notepad.exe": "notepad",
"NVDisplay.Container.exe": "NVIDIA",
"wpsoffice.exe": "WPSoffice",
"SogouImeBroker.exe": "搜狗拼音输入法",
"SogouCloud.exe": "搜狗拼音输入法",
"QQ.exe": "腾讯QQ",
"ChsIME.exe": "微软简体中文输入法",
"UClient.exe": "UClient客户端",
"D4Ser_ICBC.exe": "中国工商银行U盾服务软件",
"FlashHelperService.exe": "Flash",
"360DesktopService64.exe": "360桌面小助手",
"Microsoft.Photos.exe": "Photos",
"photoshop.exe": "Adobe Photoshop",
"360Newsld.exe": "360新闻",
"360DayPop.exe": "360早间推荐",
"360huabao.exe": "360画报-屏幕保护程序",
"dwm.exe": "桌面窗口管理器",
"SunloginClient.exe": "向日葵远程控制软件",
"向日葵.exe": "向日葵远程控制软件",
"sunlogin.exe": "花生壳",
"SunloginClient_10.3.exe": "向日葵远程控制软件",
"Thunder.exe": "迅雷下载器",
"vmware-vmx.exe": "VMware虚拟机",
"yqzs.exe": "亿企助手",
"kgservice.exe": "酷狗音乐",
"WXWork.exe": "企业微信",
"MultiTip.exe": "360浏览器新闻窗口",
"FlashHelperService.exe": "FlashHelperService右下角弹窗",
"360DayPop.exe": "360每日趣玩中间弹窗",
"GameMaster.exe": "360游戏管家中间弹窗",
"360Clock.exe": "360日历",
"KwService.exe": "酷我音乐盒",
"kuMusi.exe": "酷我音乐盒",
"SoftMgrLite.exe": "360小助手",
"NewSearchLite.exe": "极速搜索",
"iStylePDF.exe": "iStylePDF阅读器",
"WnCloud.exe": "五笔输入法",
"360rps.exe": "360任务管理器",
"360sd.exe": "360任务管理器",
"360rp.exe": "360任务管理器",
"SoftMgrLite.exe": "360开机小助手",
"WXWorkWeb.exe": "企业微信",
"360zip.exe": "360压缩",
"WinRAR.exe": "winrar压缩",
"MicrosoftEdgeUpdate.exe": "Edge浏览器",
"360DrvMgr.exe": "360驱动大师",
"360speedldEx.exe": "360软件管家",
"Video.UI.exe": "win10自带的视频播放工具",
"360DesktopLite.exe": "360桌面",
"EsCqcbUserTool.exe": "重庆银行",
"360leakfixer.exe": "360安全卫士漏洞补丁检测模块",
"KGPMService.exe": "浏览器核心服务",
"TBSecSvc.exe": "阿里巴巴网购安全服务",
"HPStatusAlerts.exe": "HPStatusAlerts",
"pdfspeedup.exe": "AdobePDF阅读器",
"360SettingCenter.exe": "360安全卫士设置中心",
"AsusUpdateCheck.exe": "华硕驱动升级检查软件",
"nortonsecurity.exe": "诺顿杀毒",
"WXDrive.exe": "企业微信",
"AlibabaProtect.exe": "阿里巴巴相关产品",
"QQPYUserCenter.exe": "QQ拼音",
"AdobeIPCBroker.exe": "Adobe 应用程序",
"node.exe": "Node",
"sqlwriter.exe": "Microsoft SQL Server",
"idea64.exe": "IDEA64",
"idea.exe": "IDEA",
"idea32.exe": "IDEA32",
"GitHubDesktop.exe": "GitHub",
"java.exe": "java",
"javac.exe": "java",
"wpscloudsvr.exe": "WPS 云服务",
"微信开发者工具.exe": "微信开发者工具",
"wechatdevtools.exe": "微信开发者工具",
"KuGou.exe": "酷狗音乐",
"360AP.exe": "360免费wifi",
"HuYanBao.exe": "护眼宝",
"YunDetectService.exe": "百度云管家/百度云网盘",
"baidunetdisk.exe": "百度网盘",
"baidunetdiskhost.exe": "百度网盘",
"ToDesk_Service.exe": "远程控制工具",
"Foxmail.exe": "Foxmail",
"vpnkit-bridge.exe": "vpnkit",
"vpnkit.exe": "vpnkit",
"com.docker.proxy.exe ": "Docker",
"docker.exe": "Docker",
"WindowsTerminal.exe": "WindowsTerminal",
"postgres.exe": "PostgreSQL数据库管理程序",
"i4Tools.exe": "爱思助手",
"vmware.exe": "VMware",
"vmware-unity-helper.exe": "VMware",
"vmware-vmx.exe": "VMware",
"WeChatPlayer.exe": "微信",
"vmware-hostd.exe": "VMware",
"vmware-usbarbitrator64.exe": "VMware",
"HUAWEI Cloud.exe": "HUAWEI Cloud",
"TIM.exe": "TIM",	
"aAvgApi.exe": "AVG",
"ackwin32.exe": "已知杀软进程,名称暂未收录",
"alertsvc.exe": "Norton AntiVirus",
"alogserv.exe": "McAfee VirusScan",
"anti-trojan.exe": "Anti-Trojan Elite",
"arr.exe": "Application Request Route",
"atguard.exe": "AntiVir",
"atupdater.exe": "已知杀软进程,名称暂未收录",
"atwatch.exe": "Mustek",
"au.exe": "NSIS",
"aupdate.exe": "Symantec",
"auto-protect.nav80try.exe": "已知杀软进程,名称暂未收录",
"autodown.exe": "AntiVirus AutoUpdater",
"avconsol.exe": "McAfee",
"avgcc32.exe": "AVG",
"avgctrl.exe": "AVG",
"avgemc.exe": "AVG",
"avgrsx.exe": "AVG",
"avgserv.exe": "AVG",
"avgserv9.exe": "AVG",
"avgw.exe": "AVG",
"avkpop.exe": "G DATA SOFTWARE AG",
"avkserv.exe": "G DATA SOFTWARE AG",
"avkservice.exe": "G DATA SOFTWARE AG",
"avkwctl9.exe": "G DATA SOFTWARE AG",
"avltmain.exe": "Panda Software Aplication",
"avnt.exe": "H+BEDV Datentechnik GmbH",
"avp32.exe": "Kaspersky Anti-Virus",
"avpcc.exe": " Kaspersky AntiVirus",
"avpdos32.exe": " Kaspersky AntiVirus",
"avpm.exe": " Kaspersky AntiVirus",
"avptc32.exe": " Kaspersky AntiVirus",
"avpupd.exe": " Kaspersky AntiVirus",
"avsynmgr.exe": "McAfee",
"avwin.exe": " H+BEDV",
"bargains.exe": "Exact Advertising SpyWare",
"beagle.exe": "Avast",
"blackd.exe": "BlackICE",
"blackice.exe": "BlackICE",
"blink.exe": "micromedia",
"blss.exe": "CBlaster",
"bootwarn.exe": "Symantec",
"bpc.exe": "Grokster",
"brasil.exe": "Exact Advertising",
"ccevtmgr.exe": "Norton Internet Security",
"cdp.exe": "CyberLink Corp.",
"cfd.exe": "Motive Communications",
"cfgwiz.exe": " Norton AntiVirus",
"claw95.exe": "已知杀软进程,名称暂未收录",
"claw95cf.exe": "已知杀软进程,名称暂未收录",
"clean.exe": "windows流氓软件清理大师",
"cleaner.exe": "windows流氓软件清理大师",
"cleaner3.exe": "windows流氓软件清理大师",
"cleanpc.exe": "windows流氓软件清理大师",
"cpd.exe": "McAfee",
"ctrl.exe": "已知杀软进程,名称暂未收录",
"cv.exe": "已知杀软进程,名称暂未收录",
"defalert.exe": "Symantec",
"defscangui.exe": "Symantec",
"defwatch.exe": "Norton Antivirus",
"doors.exe": "已知杀软进程,名称暂未收录",
"dpf.exe": "已知杀软进程,名称暂未收录",
"dpps2.exe": "PanicWare",
"dssagent.exe": "Broderbund",
"ecengine.exe": "已知杀软进程,名称暂未收录",
"emsw.exe": "Alset Inc",
"ent.exe": "已知杀软进程,名称暂未收录",
"espwatch.exe": "已知杀软进程,名称暂未收录",
"ethereal.exe": "RationalClearCase",
"exe.avxw.exe": "已知杀软进程,名称暂未收录",
"expert.exe": "已知杀软进程,名称暂未收录",
"f-prot95.exe": "已知杀软进程,名称暂未收录",
"fameh32.exe": "F-Secure",
"fast.exe": " FastUsr",
"fch32.exe": "F-Secure",
"fih32.exe": "F-Secure",
"findviru.exe": "F-Secure",
"firewall.exe": "AshampooSoftware",
"fnrb32.exe": "F-Secure",
"fp-win.exe": " F-Prot Antivirus OnDemand",
"fsaa.exe": "F-Secure",
"fsav.exe": "F-Secure",
"fsav32.exe": "F-Secure",
"fsav530stbyb.exe": "F-Secure",
"fsav530wtbyb.exe": "F-Secure",
"fsav95.exe": "F-Secure",
"fsgk32.exe": "F-Secure",
"fsm32.exe": "F-Secure",
"fsma32.exe": "F-Secure",
"fsmb32.exe": "F-Secure",
"gbmenu.exe": "已知杀软进程,名称暂未收录",
"guard.exe": "ewido",
"guarddog.exe": "ewido",
"htlog.exe": "已知杀软进程,名称暂未收录",
"htpatch.exe": "Silicon Integrated Systems Corporation",
"hwpe.exe": "已知杀软进程,名称暂未收录",
"iamapp.exe": "Symantec",
"iamserv.exe": "Symantec",
"iamstats.exe": "Symantec",
"iedriver.exe": " Urlblaze.com",
"iface.exe": "Panda Antivirus Module",
"infus.exe": "Infus Dialer",
"infwin.exe": "Msviewparasite",
"intdel.exe": "Inet Delivery",
"intren.exe": "已知杀软进程,名称暂未收录",
"jammer.exe": "已知杀软进程,名称暂未收录",
"kavpf.exe": "Kapersky",
"kazza.exe": "Kapersky",
"keenvalue.exe": "EUNIVERSE INC",
"launcher.exe": "Intercort Systems",
"ldpro.exe": "已知杀软进程,名称暂未收录",
"ldscan.exe": "Windows Trojans Inspector",
"localnet.exe": "已知杀软进程,名称暂未收录",
"luall.exe": "Symantec",
"luau.exe": "Symantec",
"lucomserver.exe": "Norton",
"mcagent.exe": "McAfee",
"mcmnhdlr.exe": "McAfee",
"mctool.exe": "McAfee",
"mcupdate.exe": "McAfee",
"mcvsrte.exe": "McAfee",
"mcvsshld.exe": "McAfee",
"mfin32.exe": "MyFreeInternetUpdate",
"mfw2en.exe": "MyFreeInternetUpdate",
"mfweng3.02d30.exe": "MyFreeInternetUpdate",
"mgavrtcl.exe": "McAfee",
"mgavrte.exe": "McAfee",
"mghtml.exe": "McAfee",
"mgui.exe": "BullGuard",
"minilog.exe": "Zone Labs Inc",
"mmod.exe": "EzulaInc",
"mostat.exe": "WurldMediaInc",
"mpfagent.exe": "McAfee",
"mpfservice.exe": "McAfee",
"mpftray.exe": "McAfee",
"mscache.exe": "Integrated Search Technologies Spyware",
"mscman.exe": "OdysseusMarketingInc",
"msmgt.exe": "Total Velocity Spyware",
"msvxd.exe": "W32/Datom-A",
"mwatch.exe": "已知杀软进程,名称暂未收录",
"nav.exe": "Reuters Limited",
"navapsvc.exe": "Norton AntiVirus",
"navapw32.exe": "Norton AntiVirus",
"navw32.exe": "Norton Antivirus",
"ndd32.exe": "诺顿磁盘医生",
"neowatchlog.exe": "已知杀软进程,名称暂未收录",
"netutils.exe": "已知杀软进程,名称暂未收录",
"nisserv.exe": "Norton",
"nisum.exe": "Norton",
"nmain.exe": "Norton",
"nod32.exe": "ESET Smart Security",
"norton_internet_secu_3.0_407.exe": "已知杀软进程,名称暂未收录",
"notstart.exe": "已知杀软进程,名称暂未收录",
"nprotect.exe": "Symantec",
"npscheck.exe": "Norton",
"npssvc.exe": "Norton",
"ntrtscan.exe": "趋势反病毒应用程序",
"nui.exe": "已知杀软进程,名称暂未收录",
"otfix.exe": "已知杀软进程,名称暂未收录",
"outpostinstall.exe": "Outpost",
"patch.exe": "趋势科技",
"pavw.exe": "已知杀软进程,名称暂未收录",
"pcscan.exe": "趋势科技",
"pdsetup.exe": "已知杀软进程,名称暂未收录",
"persfw.exe": "Tiny Personal Firewall",
"pgmonitr.exe": "PromulGate SpyWare",
"pingscan.exe": "已知杀软进程,名称暂未收录",
"platin.exe": "已知杀软进程,名称暂未收录",
"pop3trap.exe": "PC-cillin",
"poproxy.exe": "NortonAntiVirus",
"popscan.exe": "已知杀软进程,名称暂未收录",
"powerscan.exe": "Integrated Search Technologies",
"ppinupdt.exe": "已知杀软进程,名称暂未收录",
"pptbc.exe": "已知杀软进程,名称暂未收录",
"ppvstop.exe": "已知杀软进程,名称暂未收录",
"prizesurfer.exe": "Prizesurfer",
"prmt.exe": "OpiStat",
"prmvr.exe": "Adtomi",
"processmonitor.exe": "Sysinternals",
"proport.exe": "已知杀软进程,名称暂未收录",
"protectx.exe": "ProtectX",
"pspf.exe": "已知杀软进程,名称暂未收录",
"purge.exe": "已知杀软进程,名称暂未收录",
"qconsole.exe": "Norton AntiVirus Quarantine Console",
"qserver.exe": "Norton Internet Security",
"rapapp.exe": "BlackICE",
"rb32.exe": "RapidBlaster",
"rcsync.exe": "PrizeSurfer",
"realmon.exe": "Realmon ",
"rescue.exe": "已知杀软进程,名称暂未收录",
"rescue32.exe": "卡巴斯基互联网安全套装",
"rshell.exe": "已知杀软进程,名称暂未收录",
"rtvscn95.exe": "Real-time virus scanner ",
"rulaunch.exe": "McAfee User Interface",
"run32dll.exe": "PAL PC Spy",
"safeweb.exe": "PSafe Tecnologia",
"sbserv.exe": "Norton Antivirus",
"scrscan.exe": "360杀毒",
"sfc.exe": "System file checker",
"sh.exe": "MKS Toolkit for Win3",
"showbehind.exe": "MicroSmarts Enterprise Component ",
"soap.exe": "System Soap Pro",
"sofi.exe": "已知杀软进程,名称暂未收录",
"sperm.exe": "已知杀软进程,名称暂未收录",
"supporter5.exe": "eScorcher反病毒",
"symproxysvc.exe": "Symantec",
"symtray.exe": "Symantec",
"tbscan.exe": "ThunderBYTE",
"tc.exe": "TimeCalende",
"titanin.exe": "TitanHide",
"tvmd.exe": "Total Velocity",
"tvtmd.exe": " Total Velocity",
"vettray.exe": "eTrust",
"vir-help.exe": "已知杀软进程,名称暂未收录",
"vnpc3000.exe": "已知杀软进程,名称暂未收录",
"vpc32.exe": "Symantec",
"vpc42.exe": "Symantec",
"vshwin32.exe": "McAfee",
"vsmain.exe": "McAfee",
"vsstat.exe": "McAfee",
"wfindv32.exe": "已知杀软进程,名称暂未收录",
"zapro.exe": "Zone Alarm",
"zonealarm.exe": "Zone Alarm",
"AVPM.exe": "Kaspersky",
"A2CMD.exe": "Emsisoft Anti-Malware",
"A2SERVICE.exe": "a-squared free",
"A2FREE.exe": "a-squared Free",
"ADVCHK.exe": "Norton AntiVirus",
"AGB.exe": "安天防线",
"AHPROCMONSERVER.exe": "安天防线",
"AIRDEFENSE.exe": "AirDefense",
"ALERTSVC.exe": "Norton AntiVirus",
"AVIRA.exe": "小红伞杀毒",
"AMON.exe": "Tiny Personal Firewall",
"AVZ.exe": "AVZ",
"ANTIVIR.exe": "已知杀软进程,名称暂未收录",
"APVXDWIN.exe": "熊猫卫士",
"ASHMAISV.exe": "Alwil",
"ASHSERV.exe": "Avast Anti-virus",
"ASHSIMPL.exe": "AVAST!VirusCleaner",
"ASHWEBSV.exe": "Avast",
"ASWUPDSV.exe": "Avast",
"ASWSCAN.exe": "Avast",
"AVCIMAN.exe": "熊猫卫士",
"AVCONSOL.exe": "McAfee",
"AVENGINE.exe": "熊猫卫士",
"AVESVC.exe": "Avira AntiVir Security Service",
"AVEVL32.exe": "已知杀软进程,名称暂未收录",
"AVGAM.exe": "AVG",
"AVGCC.exe": "AVG",
"AVGCHSVX.exe": "AVG",
"AVGCSRVX": "AVG",
"AVGNSX.exe": "AVG",
"AVGCC32.exe": "AVG",
"AVGCTRL.exe": "AVG",
"AVGEMC.exe": "AVG",
"AVGFWSRV.exe": "AVG",
"AVGNTMGR.exe": "AVG",
"AVGSERV.exe": "AVG",
"AVGTRAY.exe": "AVG",
"AVGUPSVC.exe": "AVG",
"AVINITNT.exe": "Command AntiVirus for NT Server",
"AVPCC.exe": "Kaspersky",
"AVSERVER.exe": "Kerio MailServer",
"AVSCHED32.exe": "H+BEDV",
"AVSYNMGR.exe": "McAfee",
"AVWUPSRV.exe": "H+BEDV",
"BDSWITCH.exe": "BitDefender Module",
"BLACKD.exe": "BlackICE",
"CCEVTMGR.exe": "Symantec",
"CFP.exe": "COMODO",
"CLAMWIN.exe": "ClamWin Portable",
"CUREIT.exe": "DrWeb CureIT",
"DEFWATCH.exe": "Norton Antivirus",
"DRWADINS.exe": "Dr.Web",
"d_safe_manage.exe": "d盾", 
"d_manage.exe": "d盾", 
"pc.exe": "云锁客户端", 
"yunsuo_agent_service.exe": "云锁服务端", 
"yunsuo_agent_daemon.exe": "云锁服务端", 
"gov_defence_daemon.exe": "govdefence(网防g01)", 
"gov_defence_service.exe": "govdefence(网防g01)", 
"aliyundun.exe": "阿里云-云盾", 
"alisecguard.exe": "阿里云-云盾", 
"aliyundunupdate.exe": "阿里云-升级服务", 
"aliyun_assist_service.exe": "阿里云-云监控", 
"baradagent.exe": "腾讯云-安全监控组件", 
"sgagent.exe": "腾讯云-安全监控组件", 
"ydservice.exe": "腾讯云-云镜主机安全",
"ydlive.exe": "腾讯云-云镜主机安全", 
"ydedr.exe": "腾讯云-云镜主机安全",
"360websafe.exe": "360主机卫士", 
"qhsrv.exe": "360主机卫士", 
"qhwebshellguard.exe": "360主机卫士", 
"cloudhelper.exe": "安全狗", 
"safedogtray.exe": "安全狗", 
"safedogguardcenter.exe": "安全狗", 
"safedogupdatecenter.exe": "安全狗", 
"safedogsiteapache.exe": "网站安全狗(apache)", 
"safedogsiteiis.exe": "网站安全狗(iis)", 
"safedogserverui.exe": "服务器安全狗", 
"hws.exe": "护卫神·入侵防护系统", 
"hwsd.exe": "护卫神·入侵防护系统", 
"hws_ui.exe": "护卫神·入侵防护系统", 
"hwspanel.exe": "护卫神·入侵防护系统", 
"hipsdaemon.exe": "火绒安全软件",   
"hipstray.exe": "火绒安全软件", 
"hipslog.exe": "火绒安全软件", 
"hipsmain.exe": "火绒安全软件", 
"usysdiag.exe": "火绒安全软件", 
"wsctrl.exe": "火绒安全软件", 
"qqpcrtp.exe": "腾讯电脑管家", 
"qqpctray.exe": "腾讯电脑管家", 
"qqpcnetflow.exe": "腾讯电脑管家", 
"qqpcrealtimespeedup.exe": "腾讯电脑管家", 
"360sd.exe": "360杀毒", 
"360rp.exe": "360杀毒", 
"360safe.exe": "360安全卫士", 
"360tray.exe": "360实时保护", 
"liveupdate360.exe": "360更新程序", 
"zhudongfangyu.exe": "360主动防御", 
"360safebox.exe": "360保险箱主程序", 
"360skylarsvc.exe": "360天擎终端安全管理系统", 
"wdswfsafe.exe": "360杀毒-网盾", 
"QHActiveDefense.exe": "360国际版", 
"360EntMisc.exe": "360(奇安信)天擎", 
"360EntClient.exe": "天擎EDR Agent", 
"edr_sec_plan.exe": "深信服EDR Agent", 
"edr_monitor.exe": "深信服EDR Agent", 
"edr_agent.exe": "深信服EDR Agent", 
"ESCCControl.exe": "启明星辰天珣EDR Agent", 
"ESCC.exe": "启明星辰天珣EDR Agent", 
"ESAV.exe": "启明星辰天珣EDR Agent", 
"ESCCIndex.exe": "启明星辰天珣EDR Agent", 
"savmain.exe": "Sophos杀毒", 
"savprogress.exe": "Sophos杀毒", 
"Sophos UI.exe": "Sophos杀毒", 
"SophosCleanM.exe": "Sophos杀毒", 
"SophosFileScanner.exe": "Sophos杀毒", 
"SophosOsquery.exe": "Sophos杀毒", 
"SophosNtpService.exe": "Sophos杀毒", 
"SophosFS.exe": "Sophos File Scanner Service", 
"SophosHealth.exe": "Sophos Health Service", 
"SophosSafestore64.exe": "Sophos Safestore Service", 
"SEDService.exe": "Sophos Endpoint Defense Service", 
"ALsvc.exe": "Sophos AutoUpdate Service", 
"SophosCleanM64.exe": "Sophos Clean Service", 
"McsAgent.exe": "Sophos MCS Agent", 
"McsClient.exe": "Sophos MCS Client", 
"SSPService.exe": "Sophos System Protection Service", 
"swc_service.exe": "Sophos Web Control Service", 
"SophosFIMService.exe": "Sophos FIM", 
"sdcservice.exe": "Sophos Device Control Service", 
"mbam.exe": "malwarebytes杀毒", 
"mbamtray.exe": "malwarebytes杀毒", 
"mbamservice.exe": "malwarebytes杀毒", 
"tmbmsrv.exe": "pc-cillin趋势反病毒", 
"ntrtscan.exe": "pc-cillin趋势反病毒", 
"vstskmgr.exe": "mcafee(麦咖啡)", 
"mcshield.exe": "mcafee(麦咖啡)", 
"mfevtps.exe": "mcafee(麦咖啡)", 
"mfeann.exe": "mcafee(麦咖啡)", 
"tbmon.exe": "mcafee(麦咖啡)", 
"shstat.exe": "mcafee(麦咖啡)", 
"mctray.exe": "mcafee(麦咖啡)", 
"udaterui.exe": "mcafee(麦咖啡)", 
"naprdmgr.exe": "mcafee(麦咖啡)", 
"engineserver.exe": "mcafee(麦咖啡)", 
"frameworkservice.exe": "mcafee(麦咖啡)", 
"avk.exe": "gdata安全防护软件", 
"gdscan.exe": "gdata安全防护软件", 
"avkwctl.exe": "gdata安全防护软件", 
"avkcl.exe": "gdata安全防护软件", 
"avkproxy.exe": "gdata安全防护软件", 
"avkbackupservice.exe": "gdata安全防护软件", 
"ccevtmgr.exe": "symantec(赛门铁克)", 
"ccsetmgr.exe": "symantec(赛门铁克)", 
"ccsvchst.exe": "symantec(赛门铁克) 或 norton(诺顿杀毒)", 
"rtvscan.exe": "symantec(赛门铁克) 或 norton(诺顿杀毒)", 
"smc.exe": "symantec(赛门铁克)", 
"smcgui.exe": "symantec(赛门铁克)", 
"snac.exe": "symantec(赛门铁克)", 
"symcorpui.exe": "symantec(赛门铁克)", 
"msmpeng.exe": "windows defender", 
"nissrv.exe": "windows defender", 
"mssense.exe": "windows defender", 
"msseces.exe": "windows defender", 
"mpcmdrun.exe": "windows defender", 
"msascui.exe": "windows defender", 
"msascuil.exe": "windows defender", 
"securityhealthservice.exe": "windows defender", 
"smartscreen.exe": "windows defender smartscreen", 
"avp.exe": "kaspersky(卡巴斯基)", 
"kavfs.exe": "kaspersky(卡巴斯基)", 
"klnagent.exe": "kaspersky(卡巴斯基)", 
"kavtray.exe": "kaspersky(卡巴斯基)", 
"kavfswp.exe": "kaspersky(卡巴斯基)", 
"ekrn.exe": "eset nod32防毒", 
"egui.exe": "eset nod32防毒", 
"eshasrv.exe": "eset nod32防毒", 
"eguiproxy.exe": "eset nod32防毒", 
"avg.exe": "avg杀毒", 
"avgwdsvc.exe": "avg杀毒", 
"avastui.exe": "avast!5主程序", 
"ashdisp.exe": "avast网络安全", 
"clamtray.exe": "clemwin free antivirus", 
"clamscan.exe": "clemwin free antivirus", 
"avcenter.exe": "avira(小红伞)", 
"avguard.exe": "avira(小红伞)", 
"avgnt.exe": "avira(小红伞)", 
"sched.exe": "avira(小红伞)", 
"bddownloader.exe": "百度卫士", 
"baidusafetray.exe": "百度卫士", 
"baiduansvx.exe": "百度卫士-主进程", 
"baidusd.exe": "百度杀毒-主程序", 
"baidusdsvc.exe": "百度杀毒-服务进程", 
"baidusdtray.exe": "百度杀毒-托盘进程", 
"f-prot.exe": "f-prot杀毒", 
"vba32lder.exe": "vb32杀毒", 
"k7tsecurity.exe": "k7杀毒", 
"iptray.exe": "immunet杀毒", 
"cmctrayicon.exe": "cmc杀毒", 
"bkavservice.exe": "bkav杀毒", 
"nspupsvc.exe": "nprotect杀毒", 
"a2guard.exe": "a-squared杀毒", 
"ad-watch.exe": "lavasoft杀毒", 
"unthreat.exe": "unthreat杀毒", 
"psafesystray.exe": "psafe反病毒", 
"patray.exe": "ahnlab安博士杀毒", 
"v3svc.exe": "ahnlab安博士v3杀毒", 
"cleaner8.exe": "the cleaner杀毒", 
"mongoosagui.exe": "mongoosa杀毒", 
"secenter.exe": "bitdefender杀毒", 
"ayagent.exe": "alyac韩国胶囊杀毒", 
"ksafe.exe": "金山卫士", 
"kvmonxp.exe": "江民杀毒", 
"ravmon.exe": "瑞星杀毒", 
"ravmond.exe": "瑞星杀毒", 
"kxescore.exe": "金山毒霸", 
"kupdata.exe": "金山毒霸", 
"kxetray.exe": "金山毒霸", 
"kwsprotect64.exe": "金山毒霸", 
"ksafetray.exe": "金山卫士", 
"knsdtray.exe": "可牛杀毒", 
"sbamsvc.exe": "vipre杀毒", 
"remupd.exe": "熊猫卫士杀毒", 
"spidernt.exe": "dr.web杀毒", 
"quhlpsvc.exe": "quickheal杀毒", 
"fsavgui.exe": "f-secure冰岛杀毒", 
"f-secure.exe": "f-secure冰岛杀毒", 
"arcatasksservice.exe": "arcavir杀毒", 
"vsserv.exe": "bitdefender比特梵德杀毒", 
"avwatchservice.exe": "virusfighter杀毒", 
"ns.exe": "norton诺顿杀毒", 
"ccapp.exe": "norton诺顿杀毒", 
"vptray.exe": "norton病毒防火墙-盾牌图标程序", 
"npfmntor.exe": "norton杀毒软件相关进程", 
"ccregvfy.exe": "norton杀毒软件自身完整性检查程序", 
"sndsrvc.exe": "symantec shared诺顿邮件防火墙软件", 
"spbbcsvc.exe": "symantec shared诺顿邮件防火墙软件", 
"symlcsvc.exe": "symantec shared诺顿邮件防火墙软件", 
"coranticontrolcenter32.exe": "coranti2012杀毒", 
"cksoftshiedantivirus4.exe": "shield antivirus杀毒", 
"spywareterminatorshield.exe": "spywareterminator杀毒", 
"usbkiller.exe": "u盘杀毒专家", 
"ast.exe": "超级巡警", 
"fortitray.exe": "飞塔", 
"gg.exe": "巨盾网游安全盾", 
"adam.exe": "绿鹰安全精灵", 
"kpfwtray.exe": "金山网镖", 
"beikesan.exe": "贝壳云安全", 
"parmor.exe": "木马克星", 
"iparmor.exe": "木马克星", 
"kswebshield.exe": "金山网盾", 
"trojanhunter.exe": "木马猎手", 
"webscanx.exe": "网络病毒克星", 
"ananwidget.exe": "墨者安全专家", 
"pfw.exe": "天网防火墙", 
"cfp.exe": "comodo科摩多", 
"mpmon.exe": "微点主动防御", 
"rfwmain.exe": "瑞星防火墙", 
"sphinx.exe": "sphinx防火墙", 
"vsmon.exe": "zonealarm防火墙", 
"fyfirewall.exe": "风云防火墙", 
"acs.exe": "outpost防火墙", 
"outpost.exe": "outpost防火墙",
"360tray.exe": "360安全卫士-实时保护",
"360tray.exe": "360安全卫士-实时保护",
"360safe.exe": "360安全卫士-主程序",
"ZhuDongFangYu.exe": "360安全卫士-主动防御",
"360sd.exe": "360杀毒",
"a2guard.exe": "a-squared杀毒",
"ad-watch.exe": "Lavasoft杀毒",
"cleaner8.exe": "The Cleaner杀毒",
"vba32lder.exe": "vb32杀毒",
"MongoosaGUI.exe": "Mongoosa杀毒",
"CorantiControlCenter32.exe": "Coranti2012杀毒",
"F-PROT.exe": "F-Prot AntiVirus",
"CMCTrayIcon.exe": "CMC杀毒",
"K7TSecurity.exe": "K7杀毒",
"UnThreat.exe": "UnThreat杀毒",
"CKSoftShiedAntivirus4.exe": "Shield Antivirus杀毒",
"AVWatchService.exe": "VIRUSfighter杀毒",
"ArcaTasksService.exe": "ArcaVir杀毒",
"iptray.exe": "Immunet杀毒",
"PSafeSysTray.exe": "PSafe杀毒",
"nspupsvc.exe": "nProtect杀毒",
"SpywareTerminatorShield.exe": "SpywareTerminator反间谍软件",
"BKavService.exe": "Bkav杀毒",
"MsMpEng.exe": "Microsoft Security Essentials",
"SBAMSvc.exe": "VIPRE",
"ccSvcHst.exe": "Norton杀毒",
"f-secure.exe": "冰岛",
"avp.exe": "Kaspersky",
"KvMonXP.exe": "江民杀毒",
"RavMonD.exe": "瑞星杀毒",
"Mcshield.exe": "McAfee",
"Tbmon.exe": "McAfee",
"Frameworkservice.exe": "McAfee",
"egui.exe": "ESET NOD32",
"ekrn.exe": "ESET NOD32",
"eguiProxy.exe": "ESET NOD32",
"kxetray.exe": "金山毒霸",
"knsdtray.exe": "可牛杀毒",
"TMBMSRV.exe": "趋势杀毒",
"avcenter.exe": "Avira(小红伞)",
"avguard.exe": "Avira(小红伞)",
"avgnt.exe": "Avira(小红伞)",
"sched.exe": "Avira(小红伞)",
"ashDisp.exe": "Avast网络安全",
"rtvscan.exe": "诺顿杀毒",
"ccapp.exe": "SymantecNorton",
"NPFMntor.exe": "Norton杀毒软件",
"ccSetMgr.exe": "赛门铁克",
"ccRegVfy.exe": "Norton杀毒软件",
"ksafe.exe": "金山卫士",
"QQPCRTP.exe": "QQ电脑管家",
"avgwdsvc.exe": "AVG杀毒",
"QUHLPSVC.exe": "QUICK HEAL杀毒",
"mssecess.exe": "微软杀毒",
"SavProgress.exe": "Sophos杀毒",
"SophosUI.exe": "Sophos杀毒",
"SophosFS.exe": "Sophos杀毒",
"SophosHealth.exe": "Sophos杀毒",
"SophosSafestore64.exe": "Sophos杀毒",
"SophosCleanM.exe": "Sophos杀毒",
"fsavgui.exe": "F-Secure杀毒",
"vsserv.exe": "比特梵德",
"remupd.exe": "熊猫卫士",
"FortiTray.exe": "飞塔",
"safedog.exe": "安全狗",
"parmor.exe": "木马克星",
"Iparmor.exe.exe": "木马克星",
"beikesan.exe": "贝壳云安全",
"KSWebShield.exe": "金山网盾",
"TrojanHunter.exe": "木马猎手",
"GG.exe": "巨盾网游安全盾",
"adam.exe": "绿鹰安全精灵",
"AST.exe": "超级巡警",
"ananwidget.exe": "墨者安全专家",
"AVK.exe": "AntiVirusKit",
"avg.exe": "AVG Anti-Virus",
"spidernt.exe": "Dr.web",
"avgaurd.exe": "Avira Antivir",
"vsmon.exe": "Zone Alarm",
"cpf.exe": "Comodo",
"outpost.exe": "Outpost Firewall",
"rfwmain.exe": "瑞星防火墙",
"kpfwtray.exe": "金山网镖",
"FYFireWall.exe": "风云防火墙",
"MPMon.exe": "微点主动防御",
"pfw.exe": "天网防火墙",
"BaiduSdSvc.exe": "百度杀毒-服务进程",
"BaiduSdTray.exe": "百度杀毒-托盘进程",
"BaiduSd.exe": "百度杀毒-主程序",
"SafeDogGuardCenter.exe": "安全狗",
"safedogupdatecenter.exe": "安全狗",
"safedogguardcenter.exe": "安全狗",
"SafeDogSiteIIS.exe": "安全狗",
"SafeDogTray.exe": "安全狗",
"SafeDogServerUI.exe": "安全狗",
"D_Safe_Manage.exe": "D盾",
"d_manage.exe": "D盾",
"yunsuo_agent_service.exe": "云锁",
"yunsuo_agent_daemon.exe": "云锁",
"HwsPanel.exe": "护卫神",
"hws_ui.exe": "护卫神",
"hws.exe": "护卫神",
"hwsd.exe": "护卫神",
"hipstray.exe": "火绒",
"wsctrl.exe": "火绒",
"usysdiag.exe": "火绒",
"SPHINX.exe": "SPHINX防火墙",
"bddownloader.exe": "百度卫士",
"baiduansvx.exe": "百度卫士-主进程",
"AvastUI.exe": "Avast!5主程序",
"emet_agent.exe": "EMET",
"emet_service.exe": "EMET",
"firesvc.exe": "McAfee",
"firetray.exe": "McAfee",
"hipsvc.exe": "McAfee",
"mfevtps.exe": "McAfee",
"mcafeefire.exe": "McAfee",
"scan32.exe": "McAfee",
"shstat.exe": "McAfee",
"vstskmgr.exe": "McAfee",
"engineserver.exe": "McAfee",
"mfeann.exe": "McAfee",
"mcscript.exe": "McAfee",
"updaterui.exe": "McAfee",
"udaterui.exe": "McAfee",
"naprdmgr.exe": "McAfee",
"cleanup.exe": "McAfee",
"cmdagent.exe": "McAfee",
"frminst.exe": "McAfee",
"mcscript_inuse.exe": "McAfee",
"mctray.exe": "McAfee",
"_avp32.exe": "卡巴斯基",
"_avpcc.exe": "卡巴斯基",
"_avpm.exe": "卡巴斯基",
"DRWEB.exe": "Dr.Web",
"DEFENDERDAEMON.exe": "ShadowDefender",
"EWIDOCTRL.exe": "Ewido Security Suite",
"EZANTIVIRUSREGISTRATIONCHECK.exe": "e-Trust Antivirus",
"FIREWALL.exe": "AshampooSoftware",
"FPROTTRAY.exe": "F-PROT Antivirus",
"FPWIN.exe": "Verizon",
"FRESHCLAM.exe": "ClamAV",
"FSAV32.exe": "F-Secure",
"FSBWSYS.exe": "F-secure",
"FSDFWD.exe": "F-Secure",
"FSGK32.exe": "F-Secure",
"FSGK32ST.exe": "F-Secure",
"FSMA32.exe": "F-Secure",
"FSMB32.exe": "F-Secure",
"FSSM32.exe": "F-Secure",
"GUARDGUI.exe": "网游保镖",
"GUARDNT.exe": "IKARUS",
"IAMAPP.exe": "Symantec",
"INOCIT.exe": "eTrust",
"INORPC.exe": "eTrust",
"INORT.exe": "eTrust",
"INOTASK.exe": "eTrust",
"INOUPTNG.exe": "eTrust",
"ISAFE.exe": "eTrust",
"KAV.exe": "Kaspersky",
"KAVMM.exe": "Kaspersky",
"KAVPF.exe": "Kaspersky",
"KAVPFW.exe": "Kaspersky",
"KAVSTART.exe": "Kaspersky",
"KAVSVC.exe": "Kaspersky",
"KAVSVCUI.exe": "Kaspersky",
"KMAILMON.exe": "金山毒霸",
"MCAGENT.exe": "McAfee",
"MCMNHDLR.exe": "McAfee",
"MCREGWIZ.exe": "McAfee",
"MCUPDATE.exe": "McAfee",
"MCVSSHLD.exe": "McAfee",
"MINILOG.exe": "Zone Alarm",
"MYAGTSVC.exe": "McAfee",
"MYAGTTRY.exe": "McAfee",
"NAVAPSVC.exe": "Norton",
"NAVAPW32.exe": "Norton",
"NAVLU32.exe": "Norton",
"NAVW32.exe": "Norton Antivirus",
"NEOWATCHLOG.exe": "NeoWatch",
"NEOWATCHTRAY.exe": "NeoWatch",
"NISSERV.exe": "Norton",
"NISUM.exe": "Norton",
"NMAIN.exe": "Norton",
"NOD32.exe": "ESET NOD32",
"NPFMSG.exe": "Norman个人防火墙",
"NPROTECT.exe": "Symantec",
"NSMDTR.exe": "Norton",
"NTRTSCAN.exe": "趋势科技",
"OFCPFWSVC.exe": "OfficeScanNT",
"ONLINENT.exe": "已知杀软进程,名称暂未收录",
"OP_MON.exe": " OutpostFirewall",
"PAVFIRES.exe": "熊猫卫士",
"PAVFNSVR.exe": "熊猫卫士",
"PAVKRE.exe": "熊猫卫士",
"PAVPROT.exe": "熊猫卫士",
"PAVPROXY.exe": "熊猫卫士",
"PAVPRSRV.exe": "熊猫卫士",
"PAVSRV51.exe": "熊猫卫士",
"PAVSS.exe": "熊猫卫士",
"PCCGUIDE.exe": "PC-cillin",
"PCCIOMON.exe": "PC-cillin",
"PCCNTMON.exe": "PC-cillin",
"PCCPFW.exe": "趋势科技",
"PCCTLCOM.exe": "趋势科技",
"PCTAV.exe": "PC Tools AntiVirus",
"PERSFW.exe": "Tiny Personal Firewall",
"PERVAC.exe": "已知杀软进程,名称暂未收录",
"PESTPATROL.exe": "Ikarus",
"PREVSRV.exe": "熊猫卫士",
"RTVSCN95.exe": "Real-time Virus Scanner",
"SAVADMINSERVICE.exe": "SAV",
"SAVMAIN.exe": "SAV",
"SAVSCAN.exe": "SAV",
"SDHELP.exe": "Spyware Doctor",
"SHSTAT.exe": "McAfee",
"SPBBCSVC.exe": "Symantec",
"SPIDERCPL.exe": "Dr.Web",
"SPIDERML.exe": "Dr.Web",
"SPIDERUI.exe": "Dr.Web",
"SPYBOTSD.exe": "Spybot ",
"SWAGENT.exe": "SonicWALL",
"SWDOCTOR.exe": "SonicWALL",
"SWNETSUP.exe": "Sophos",
"SYMLCSVC.exe": "Symantec",
"SYMPROXYSVC.exe": "Symantec",
"SYMSPORT.exe": "Sysmantec",
"SYMWSC.exe": "Sysmantec",
"SYNMGR.exe": "Sysmantec",
"TMLISTEN.exe": "趋势科技",
"TMNTSRV.exe": "趋势科技",
"TMPROXY.exe": "趋势科技",
"TNBUTIL.exe": "Anti-Virus",
"VBA32ECM.exe": "已知杀软进程,名称暂未收录",
"VBA32IFS.exe": "已知杀软进程,名称暂未收录",
"VBA32PP3.exe": "已知杀软进程,名称暂未收录",
"VCRMON.exe": "VirusChaser",
"VRMONNT.exe": "HAURI",
"VRMONSVC.exe": "HAURI",
"VSHWIN32.exe": "McAfee",
"VSSTAT.exe": "McAfee",
"XCOMMSVR.exe": "BitDefender",
"ZONEALARM.exe": "Zone Alarm",
"360rp.exe": "360杀毒",
"afwServ.exe": " Avast Antivirus",
"safeboxTray.exe": "360杀毒",
"360safebox.exe": "360杀毒",
"QQPCTray.exe": "QQ电脑管家",
"KSafeTray.exe": "金山毒霸",
"KSafeSvc.exe": "金山毒霸",
"KWatch.exe": "金山毒霸",
"gov_defence_service.exe": "云锁",
"gov_defence_daemon.exe": "云锁",
"smartscreen.exe": "Windows Defender",
"finalshell.exe": "finalshell终端管理",
"navicat.exe": "数据库管理",
"AliSecGuard.exe": "阿里云盾",
"AliYunDunUpdate.exe": "阿里云盾",
"AliYunDun.exe": "阿里云盾",
"CmsGoAgent.windows-amd64.exe": "阿里云监控",
};
